### ISSUE TITLE
No valid Tester Response was found

### ISSUE THREAD

**Issue by AjayShanker-geek** [nus-cs2113-AY2425S1/forum#52] opened 2024-11-20 08:44 UTC
Error: `No valid Tester Response was found. Please contact the teaching team for assistance.`

Only logical reason is that I submitted the bug at 6:01pm

<img width="1909" alt="Screenshot 2024-11-20 at 4 41 40 PM" src="https://github.com/user-attachments/assets/09b0bba3-b940-40f1-ba8e-1beea83310c3">

**Comment by okkhoy** [comment] 2024-11-20 10:37
Duplicate of #51

**Closed as completed by okkhoy** 2024-11-20 10:37 UTC
Labels: type-HelpRequest :sos:
